Feature/1 add firebase sdk (#7)
* feature(dependencies): installed firebase

* feature(depencencies): installed dotenv support

* feature(auth): added firebase auth support

Added firebase plugin for NUXT3. Corresponding API keys and other sensitive information is included in the /.env file

* fix(auth): fixed firbase SDK connection

Added Firebase secrets like API key to /.env and correctly used them for firebase plugin. Make sure to test if secure and not publicly available before production

* feature(auth): added firebase auth composable

Added Firebase authentication composable for registering and signing in firebase users

* fix(auth): fixed firebase auth functions

fixed firebase auth functions that didnt seem to work properly. these must be used withing an async onMounted life-cycle hook

* fix: fixed spacing in code

* fix(env): fixed incorrect database environment variable name

* feat(database): hydrated application for firebase database connection

* fix(CI): Exit with code 1 if lint in actions fails

diff --git a/.github/workflows/lintfix.yml b/.github/workflows/lintfix.yml
--- a/.github/workflows/lintfix.yml
+++ b/.github/workflows/lintfix.yml
@@ -23,3 +23,7 @@ jobs:
 
       - name: Run lint and fix
         run: npm run lintfix
+
+      - name: Cancel push on failure
+        if: ${{ failure() }}
+        run: echo "Linting and fixing failed. Cancelling push." && exit 1
